<a href="https://colab.research.google.com/github/Ayush-Khamrui/AI-ML-Full-Preparation/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

### Definition:

NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

### Use Cases in Machine Learning and Data Science:

**Machine Learning:** NumPy arrays are used to store and manipulate data for training machine learning models, like representing images, audio and text as numerical data.
**Data Science:** Used for data cleaning, transformation, and analysis, NumPy can be used to calculate statistics, reshape datasets, and perform mathematical operations on data.

### Role in Exploratory Data Analysis (EDA):

NumPy is used in EDA for tasks like calculating descriptive statistics (mean, median, standard deviation), identifying outliers, handling missing values and data manipulation before modeling.

## Import Numpy

In [2]:
import numpy as np

## Basics of Numpy

**Why Numpy arrays are used?**

**Homogeneity:** NumPy arrays are homogeneous, meaning they can only contain elements of the same data type. Python lists are heterogeneous, meaning they can contain elements of different data types.

**Performance:** NumPy arrays are significantly faster and more efficient for numerical computations than Python lists. This is because NumPy arrays are stored in contiguous memory blocks, which allows for faster access and manipulation of data.

**Functionality:** NumPy provides a wide range of mathematical and scientific functions that can be applied to arrays, such as linear algebra operations, Fourier transforms, and random number generation. Python lists have limited built-in functionality for numerical computations.

**Memory:** NumPy arrays are more memory-efficient than Python lists, especially for large datasets. This is because NumPy arrays store data in a more compact format.

In [3]:
# Creating a Numpy Array of 2-dimension
a = np.array([[1,2,3],[4,5,6]])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [ ]:
# Count the number of elements in the Numpy Array
a.size

6

In [ ]:
# Know the shape of the Numpy Array and in which fashion. 1D, 2D, 3D, ...
a.shape

(2, 3)

In [ ]:
# Check the data type of the Numpy Array
a.dtype

dtype('int64')

In [ ]:
# Transpose the Numpy Array
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# Create a Empty Numpy Array.
# The shape is defined within a tuple
# dtype defines the data type of the elements within the Numpy Array
# The resultant Numpy Array have random numbers with the following shape.
np.empty((4,5,2),dtype=float)

array([[[4.42833410e-316, 0.00000000e+000],
        [5.42978145e-321, 0.00000000e+000],
        [8.10267659e-322, 4.48782356e-316],
        [0.00000000e+000, 4.48782751e-316],
        [0.00000000e+000, 4.94065646e-324]],

       [[4.48782869e-316, 4.48779273e-316],
        [9.88131292e-324, 4.48782988e-316],
        [4.48776703e-316, 4.48779273e-316],
        [1.28457068e-322, 4.48782909e-316],
        [4.94065646e-324, 4.48782909e-316]],

       [[3.81959243e-313, 1.06099790e-313],
        [5.80527134e-321, 0.00000000e+000],
        [7.90505033e-322, 4.48777889e-316],
        [5.78550871e-321, 0.00000000e+000],
        [7.90505033e-322, 4.48783304e-316]],

       [[5.78056806e-321, 0.00000000e+000],
        [7.90505033e-322, 4.48783462e-316],
        [1.69759669e-313, 0.00000000e+000],
        [7.85564377e-322, 4.48775320e-316],
        [8.48798345e-314, 0.00000000e+000]]])

In [ ]:
# Create 1D Numpy Array with all ones
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
# Create 2D Numpy Array with all ones
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
# Create 1D Numpy Array with all zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
# Create 2D Numpy Array with all zeros
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
# We can perform mathematical operations
np.ones((2,3),dtype=float)*5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [ ]:
# Str is another data type that can be used
np.ones((2,3),dtype=str)

array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [ ]:
np.zeros((2,3),dtype=str)

array([['', '', ''],
       ['', '', '']], dtype='<U1')

In [ ]:
# bool is another data type that can be used to get the array in true or false
np.ones((2,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.zeros((2,3),dtype=bool)

array([[False, False, False],
       [False, False, False]])